name: Download dependencies and build a combined, minified source for release

on:
  push:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          mkdir lib dist
          mv node_modules/dexie/dist/dexie.js lib/dexie.js
          mv node_modules/dexie-export-import/dist/dexie-export-import.js lib/dexie-export-import.js
          mv node_modules/downloadjs/download.js lib/download.js

      - name: Minify and combine source code
        run: |
          npm run build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/yomichan-data-exporter.min.js
